apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base
- dragonfly.yaml
- hpa.yaml

patches:
- path: patch-resources.yaml

# Flux HPA конфліктує з полем replicas в Deployment, 
# тому ми не ставимо replicas: 3 тут явно, HPA сам це зробить (minReplicas: 3)