apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: course-app
spec:
  rules:
  - host: course-app.k8s.com822.dom
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: course-app
            port:
              number: 80