apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
- ../../base
  namespace.yaml
- dragonfly.yaml

# Модифікації для Dev
patches:
- target:
    kind: Ingress
    name: course-app
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: dev-course-app.k8s.com822.dom

# Кількість реплік (економимо ресурси)
replicas:
- name: course-app
  count: 1